name: New PR

on:
  pull_request_target:
    branches:
      - main
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  automate-project-columns:
    if: "!contains( github.event.pull_request.labels.*.name, 'eng')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Comment and label
        run: |
          gh pr --add-project "test this"

