name: New PR

on:
  pull_request_target:
    branches:
      - main
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  automate-project-columns:
    if: "!contains( github.event.pull_request.labels.*.name, 'eng')"
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: NR1 Quickstarts Community
          column: To do
          repo-token: ${{ secrets.GITHUB_TOKEN }}
